GET http://localhost:8080/boards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoxLCJpYXQiOjE3Nzk2MjEzMTYsImV4cCI6MTc3OTYyNDkxNn0.PVukEPoul5Y5_y-VLsOU6eN9XA0dL2fz6AIMC_E7IEA