GET http://localhost:8080/boards
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwidXNlcklkIjoxLCJpYXQiOjE3Nzk2MjEzNTUsImV4cCI6MTc3OTYyNDk1NX0.yIQ-zQq4k5t-WQpDJWqrRQLobbqVfzQg8BQIL4B00jU